### ISSUE TITLE
Release on npm

### ISSUE THREAD

**Issue by lime** [watson/airplay-server#1]
I couldn't find `airplay-server` on npm. Are you planning on releasing it? :)

**Comment by watson** [comment]
Yeah, it's been on my bad conscience for while... I've been occupied with different projects so I haven't paid that much attention to this one lately. It's still really buggy, that's why it's not released yet - thanks for reminding me. I'll make sure to get an initial version wrapped up ASAP. Hopefully in the weekend

**Comment by michaelrhodes** [comment]
@lime In the mean time, you can install the module from github like so:
`npm install watson/airplay-server`.

**Comment by watson** [comment]
Forgot to close this issue back when I released it on npm - it's available now
